DEBUG    [2019-03-18 20:41:43,367] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967137 HTTP/1.1" 200 387: message parser
DEBUG    [2019-03-18 20:41:43,407] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:41:43,798] https://api.telegram.org:443 "POST /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/sendMessage?text=https%3A%2F%2Fuk.wikipedia.org&chat_id=398480532 HTTP/1.1" 200 327: message parser
DEBUG    [2019-03-18 20:41:47,613] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:41:47,950] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:41:47,958] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:41:49,263] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:41:52,599] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:41:52,601] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:41:53,651] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:41:53,983] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:41:53,995] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:41:54,761] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:41:55,362] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:41:58,095] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:41:58,098] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:41:58,705] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:41:58,706] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:41:59,035] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:41:59,373] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:41:59,374] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:41:59,660] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:00,460] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:03,006] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:42:03,008] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:42:03,795] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:42:03,797] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:42:06,066] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:06,408] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:42:06,411] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:42:06,527] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:06,852] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:07,187] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:07,534] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:08,003] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:08,041] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:08,063] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:08,091] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:08,121] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:08,163] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:08,265] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:08,361] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:08,366] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:08,377] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:08,466] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-03-18 20:42:09,862] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:42:09,865] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:42:10,187] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:42:10,263] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:42:10,563] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:42:10,566] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:42:11,060] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:42:11,065] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:42:11,360] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:42:11,364] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:42:11,460] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
DEBUG    [2019-03-18 20:42:11,461] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:42:11,465] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
ERROR    [2019-03-18 20:42:11,466] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:42:11,560] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:42:11,564] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:42:11,661] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
DEBUG    [2019-03-18 20:42:11,661] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
DEBUG    [2019-03-18 20:42:11,661] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:42:11,667] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
ERROR    [2019-03-18 20:42:11,667] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
ERROR    [2019-03-18 20:42:11,667] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:42:11,961] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
DEBUG    [2019-03-18 20:42:11,961] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:42:11,966] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
ERROR    [2019-03-18 20:42:11,967] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-03-18 20:42:12,060] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
DEBUG    [2019-03-18 20:42:12,062] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952967138 HTTP/1.1" 409 143: message parser
ERROR    [2019-03-18 20:42:12,065] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
ERROR    [2019-03-18 20:42:12,066] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:56:51,768] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:56:52,109] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:56:52,229] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:06,324] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:06,661] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:06,665] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:07,699] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:07,996] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:08,276] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:08,921] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:10,895] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:11,063] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:11,064] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:11,244] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:11,245] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:11,342] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:11,343] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:11,569] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:11,617] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:11,618] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:12,100] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:12,261] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:12,263] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:12,532] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:12,856] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:13,421] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:13,424] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:13,446] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:13,477] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:13,508] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:13,543] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:13,632] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:13,632] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:13,727] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:13,828] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:13,844] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:13,923] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:13,931] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:14,131] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 18:57:14,601] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:14,602] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:15,021] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:15,027] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:15,445] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:15,521] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:15,921] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:15,925] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:16,221] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:16,224] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:16,821] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
DEBUG    [2019-06-11 18:57:16,822] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
DEBUG    [2019-06-11 18:57:16,823] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:16,827] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
ERROR    [2019-06-11 18:57:16,828] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
ERROR    [2019-06-11 18:57:16,833] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:17,121] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
DEBUG    [2019-06-11 18:57:17,122] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
DEBUG    [2019-06-11 18:57:17,123] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
DEBUG    [2019-06-11 18:57:17,124] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:17,125] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
ERROR    [2019-06-11 18:57:17,129] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
ERROR    [2019-06-11 18:57:17,129] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
ERROR    [2019-06-11 18:57:17,130] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:17,622] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:17,625] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:17,721] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:17,726] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:17,821] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
DEBUG    [2019-06-11 18:57:17,822] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
DEBUG    [2019-06-11 18:57:17,825] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:17,844] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
ERROR    [2019-06-11 18:57:17,921] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
ERROR    [2019-06-11 18:57:17,922] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 18:57:18,021] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968005 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 18:57:18,028] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 19:00:34,467] https://uk.wikipedia.org:443 "GET /w/api.php?srinfo=suggestion&srsearch=%D0%A1%D0%B0%D1%97%D0%B4+%D0%90%D1%83%D1%97%D1%82%D0%B0&format=json&srlimit=1&list=search&srprop=&limit=1&action=query HTTP/1.1" 200 185: message parser
DEBUG    [2019-06-11 19:00:34,471] Starting new HTTP connection (1): uk.wikipedia.org:80: message parser
DEBUG    [2019-06-11 19:00:34,477] http://uk.wikipedia.org:80 "GET /w/api.php?inprop=url&redirects=&format=json&ppprop=disambiguation&prop=info%7Cpageprops&titles=%D0%A1%D0%B0%D1%97%D0%B4+%D0%90%D1%83%D1%97%D1%82%D0%B0&action=query HTTP/1.1" 301 0: message parser
DEBUG    [2019-06-11 19:00:34,479] Starting new HTTPS connection (1): uk.wikipedia.org:443: message parser
DEBUG    [2019-06-11 19:00:34,527] https://api.telegram.org:443 "POST /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/sendMessage?text=%D0%93%D0%B0%3F&chat_id=398480532 HTTP/1.1" 200 265: message parser
DEBUG    [2019-06-11 19:00:34,533] https://uk.wikipedia.org:443 "GET /w/api.php?inprop=url&redirects=&format=json&ppprop=disambiguation&prop=info%7Cpageprops&titles=%D0%A1%D0%B0%D1%97%D0%B4+%D0%90%D1%83%D1%97%D1%82%D0%B0&action=query HTTP/1.1" 200 314: message parser
DEBUG    [2019-06-11 19:00:34,538] Starting new HTTP connection (1): uk.wikipedia.org:80: message parser
DEBUG    [2019-06-11 19:00:34,543] http://uk.wikipedia.org:80 "GET /w/api.php?format=json&exsentences=5&prop=extracts&titles=%D0%A1%D0%B0%D1%97%D0%B4+%D0%90%D1%83%D1%97%D1%82%D0%B0&action=query&explaintext= HTTP/1.1" 301 0: message parser
DEBUG    [2019-06-11 19:00:34,546] Starting new HTTPS connection (1): uk.wikipedia.org:443: message parser
DEBUG    [2019-06-11 19:00:34,637] https://uk.wikipedia.org:443 "GET /w/api.php?format=json&exsentences=5&prop=extracts&titles=%D0%A1%D0%B0%D1%97%D0%B4+%D0%90%D1%83%D1%97%D1%82%D0%B0&action=query&explaintext= HTTP/1.1" 200 317: message parser
DEBUG    [2019-06-11 19:00:34,644] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 19:00:35,010] https://api.telegram.org:443 "POST /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/sendMessage?text=%D0%A1%D0%B0%D1%97%D0%B4+%D0%90%D1%83%D1%97%D1%82%D0%B0++%28%D0%B0%D1%80%D0%B0%D0%B1.+%D8%B3%D8%B9%D9%8A%D8%AF+%D8%B9%D9%88%D9%8A%D8%B7%D8%A9%E2%80%8E%2C+%D0%BD%D0%B0%D1%80.+2+%D0%BB%D0%B8%D1%81%D1%82%D0%BE%D0%BF%D0%B0%D0%B4%D0%B0+1959%29+%E2%80%94+%D0%BC%D0%B0%D1%80%D0%BE%D0%BA%D0%BA%D0%B0%D0%BD%D1%81%D1%8C%D0%BA%D0%B8%D0%B9+%D0%BB%D0%B5%D0%B3%D0%BA%D0%BE%D0%B0%D1%82%D0%BB%D0%B5%D1%82%2C+%D0%BE%D0%BB%D1%96%D0%BC%D0%BF%D1%96%D0%B9%D1%81%D1%8C%D0%BA%D0%B8%D0%B9+%D1%87%D0%B5%D0%BC%D0%BF%D1%96%D0%BE%D0%BD.&parse_mode=HTML&chat_id=398480532 HTTP/1.1" 200 746: message parser
DEBUG    [2019-06-11 19:00:41,216] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 19:00:41,551] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968009 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 19:00:41,557] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 19:00:41,775] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 19:00:42,340] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 19:00:42,695] Starting new HTTPS connection (1): api.telegram.org:443: message parser
DEBUG    [2019-06-11 19:00:45,204] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968009 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 19:00:45,206] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 19:00:45,676] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968009 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 19:00:45,680] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
DEBUG    [2019-06-11 19:00:46,038] https://api.telegram.org:443 "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?timeout=20&offset=952968009 HTTP/1.1" 409 143: message parser
ERROR    [2019-06-11 19:00:46,039] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/mnt/nfs/labstore-secondary-tools-project/rluts/src/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
: message parser
INFO     [2019-06-11 22:25:36,751] Starting new HTTPS connection (1): api.telegram.org: /wiki message
INFO     [2019-06-11 22:25:46,028] Starting new HTTPS connection (1): api.telegram.org: /wiki message
DEBUG    [2019-06-11 22:25:46,330] "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?offset=1&timeout=20 HTTP/1.1" 409 143: /wiki message
ERROR    [2019-06-11 22:25:46,368] ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/home/rluts/PycharmProjects/ukwikibot/.env/lib/python3.6/site-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "/home/rluts/PycharmProjects/ukwikibot/.env/lib/python3.6/site-packages/telebot/__init__.py", line 276, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/rluts/PycharmProjects/ukwikibot/.env/lib/python3.6/site-packages/telebot/__init__.py", line 246, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/rluts/PycharmProjects/ukwikibot/.env/lib/python3.6/site-packages/telebot/apihelper.py", line 180, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/rluts/PycharmProjects/ukwikibot/.env/lib/python3.6/site-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/rluts/PycharmProjects/ukwikibot/.env/lib/python3.6/site-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']
: /wiki message
INFO     [2019-06-11 22:25:51,422] Starting new HTTPS connection (1): api.telegram.org: /wiki message
DEBUG    [2019-06-11 22:26:07,497] "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 387: /wiki message
INFO     [2019-06-11 22:26:07,521] Starting new HTTPS connection (1): api.telegram.org: /wiki message
DEBUG    [2019-06-11 22:26:07,982] "POST /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/sendMessage?chat_id=398480532&text=https%3A%2F%2Fuk.wikipedia.org HTTP/1.1" 200 327: /wiki message
DEBUG    [2019-06-11 22:26:26,052] "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?offset=952968010&timeout=20 HTTP/1.1" 200 435: /wiki message
INFO     [2019-06-11 22:26:26,058] Starting new HTTP connection (1): uk.wikipedia.org: /wiki message
DEBUG    [2019-06-11 22:26:26,147] "GET /w/api.php?list=search&srprop=&srlimit=1&limit=1&srsearch=%D1%85%D0%BC%D0%B5%D0%BB%D1%8C%D0%BD%D0%B8%D1%86%D1%8C%D0%BA%D0%B8%D0%B9%3F&srinfo=suggestion&format=json&action=query HTTP/1.1" 301 0: /wiki message
INFO     [2019-06-11 22:26:26,154] Starting new HTTPS connection (1): uk.wikipedia.org: /wiki message
DEBUG    [2019-06-11 22:26:26,631] "GET /w/api.php?list=search&srprop=&srlimit=1&limit=1&srsearch=%D1%85%D0%BC%D0%B5%D0%BB%D1%8C%D0%BD%D0%B8%D1%86%D1%8C%D0%BA%D0%B8%D0%B9%3F&srinfo=suggestion&format=json&action=query HTTP/1.1" 200 None: /wiki message
INFO     [2019-06-11 22:26:26,636] Starting new HTTP connection (1): uk.wikipedia.org: /wiki message
DEBUG    [2019-06-11 22:26:26,720] "GET /w/api.php?prop=info%7Cpageprops&inprop=url&ppprop=disambiguation&redirects=&titles=%D0%A5%D0%BC%D0%B5%D0%BB%D1%8C%D0%BD%D0%B8%D1%86%D1%8C%D0%BA%D0%B8%D0%B9&format=json&action=query HTTP/1.1" 301 0: /wiki message
INFO     [2019-06-11 22:26:26,726] Starting new HTTPS connection (1): uk.wikipedia.org: /wiki message
DEBUG    [2019-06-11 22:26:27,067] "GET /w/api.php?prop=info%7Cpageprops&inprop=url&ppprop=disambiguation&redirects=&titles=%D0%A5%D0%BC%D0%B5%D0%BB%D1%8C%D0%BD%D0%B8%D1%86%D1%8C%D0%BA%D0%B8%D0%B9&format=json&action=query HTTP/1.1" 200 317: /wiki message
INFO     [2019-06-11 22:26:27,075] Starting new HTTP connection (1): uk.wikipedia.org: /wiki message
DEBUG    [2019-06-11 22:26:27,156] "GET /w/api.php?prop=extracts&explaintext=&titles=%D0%A5%D0%BC%D0%B5%D0%BB%D1%8C%D0%BD%D0%B8%D1%86%D1%8C%D0%BA%D0%B8%D0%B9&exsentences=5&format=json&action=query HTTP/1.1" 301 0: /wiki message
INFO     [2019-06-11 22:26:27,161] Starting new HTTPS connection (1): uk.wikipedia.org: /wiki message
DEBUG    [2019-06-11 22:26:27,691] "GET /w/api.php?prop=extracts&explaintext=&titles=%D0%A5%D0%BC%D0%B5%D0%BB%D1%8C%D0%BD%D0%B8%D1%86%D1%8C%D0%BA%D0%B8%D0%B9&exsentences=5&format=json&action=query HTTP/1.1" 200 647: /wiki message
INFO     [2019-06-11 22:26:27,696] Starting new HTTPS connection (1): api.telegram.org: /wiki message
DEBUG    [2019-06-11 22:26:28,071] "POST /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/sendMessage?chat_id=398480532&text=%D0%A5%D0%BC%D0%B5%D0%BB%D1%8C%D0%BD%D0%B8%CC%81%D1%86%D1%8C%D0%BA%D0%B8%D0%B9+%28%D0%9C%D0%A4%D0%90%3A+%5Bxme%CA%8E%CB%88n%CC%AA%C9%AAt%CD%A1s%CA%B2k%C9%AAi%CC%AF%5D+%28+%D0%BF%D1%80%D0%BE%D1%81%D0%BB%D1%83%D1%85%D0%B0%D1%82%D0%B8%29%3B+%D0%B4%D0%BE+1793+%D1%80%D0%BE%D0%BA%D1%83+%E2%80%94+%D0%9F%D0%BB%D0%BE%D1%81%D0%BA%D0%B8%CC%81%D1%80%D1%96%D0%B2%2C+%D0%B7+1795+%D0%BF%D0%BE+1954+%E2%80%94+%D0%9F%D1%80%D0%BE%D1%81%D0%BA%D1%83%CC%81%D1%80%D1%96%D0%B2%29+%E2%80%94+%D0%B0%D0%B4%D0%BC%D1%96%D0%BD%D1%96%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D0%B8%D0%B9+%D1%86%D0%B5%D0%BD%D1%82%D1%80+%D0%A5%D0%BC%D0%B5%D0%BB%D1%8C%D0%BD%D0%B8%D1%86%D1%8C%D0%BA%D0%BE%D1%97+%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%96+%D1%96+%D0%A5%D0%BC%D0%B5%D0%BB%D1%8C%D0%BD%D0%B8%D1%86%D1%8C%D0%BA%D0%BE%D0%B3%D0%BE+%D1%80%D0%B0%D0%B9%D0%BE%D0%BD%D1%83%2C+%D0%B7%D0%BD%D0%B0%D1%87%D0%BD%D0%B8%D0%B9+%D1%96%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%87%D0%BD%D0%B8%D0%B9+%D1%82%D0%B0+%D1%81%D1%83%D1%87%D0%B0%D1%81%D0%BD%D0%B8%D0%B9+%D0%B5%D0%BA%D0%BE%D0%BD%D0%BE%D0%BC%D1%96%D1%87%D0%BD%D0%B8%D0%B9+%D1%96+%D0%BA%D1%83%D0%BB%D1%8C%D1%82%D1%83%D1%80%D0%BD%D0%B8%D0%B9+%D1%86%D0%B5%D0%BD%D1%82%D1%80+%D0%9F%D0%BE%D0%B4%D1%96%D0%BB%D0%BB%D1%8F.%0A%D0%9D%D0%B0%D1%81%D0%B5%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F+%E2%80%94+271+%D1%82%D0%B8%D1%81.+%282019%29.%0A%D0%9C%D1%96%D1%81%D1%82%D0%BE+%D1%80%D0%BE%D0%B7%D1%82%D0%B0%D1%88%D0%BE%D0%B2%D0%B0%D0%BD%D0%B5+%D0%BD%D0%B0+%D0%97%D0%B0%D1%85%D1%96%D0%B4%D0%BD%D0%BE%D0%BC%D1%83+%D0%9F%D0%BE%D0%B4%D1%96%D0%BB%D0%BB%D1%96%2C+%D0%BD%D0%B0+%D0%B1%D0%B5%D1%80%D0%B5%D0%B3%D0%B0%D1%85+%D0%9F%D1%96%D0%B2%D0%B4%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE+%D0%91%D1%83%D0%B3%D1%83%2C+%D0%B7%D0%B0+376+%D0%BA%D0%BC+%28%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%BE%D0%B1%D1%96%D0%BB%D1%8C%D0%BD%D0%B8%D0%B9+%D1%88%D0%BB%D1%8F%D1%85%29+%D0%B2%D1%96%D0%B4+%D0%9A%D0%B8%D1%94%D0%B2%D0%B0.+%D0%97%D0%B0%D0%BB%D1%96%D0%B7%D0%BD%D0%B8%D1%87%D0%BD%D0%B8%D0%B9+%D0%B2%D1%83%D0%B7%D0%BE%D0%BB+%28%D1%81%D1%82%D0%B0%D0%BD%D1%86%D1%96%D1%97+%D0%A5%D0%BC%D0%B5%D0%BB%D1%8C%D0%BD%D0%B8%D1%86%D1%8C%D0%BA%D0%B8%D0%B9%2C+%D0%93%D1%80%D0%B5%D1%87%D0%B0%D0%BD%D0%B8%29.&parse_mode=HTML HTTP/1.1" 200 2334: /wiki message
DEBUG    [2019-06-11 22:26:46,181] "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?offset=952968011&timeout=20 HTTP/1.1" 200 23: /wiki message
DEBUG    [2019-06-11 22:27:06,279] "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?offset=952968011&timeout=20 HTTP/1.1" 200 23: /wiki message
DEBUG    [2019-06-11 22:27:26,377] "GET /bot393054933:AAFVYFt0zRFbwV0TkaTItI63YOvt6YN7VFs/getUpdates?offset=952968011&timeout=20 HTTP/1.1" 200 23: /wiki message
